[[libbluray]]
arch = "aarch64"
git-tree-sha1 = "13bc1cfc1b53299a6c38477ff1aaa570dadc82c0"
libc = "glibc"
os = "linux"

    [[libbluray.download]]
    sha256 = "fb1bf524d4f5b407dbd3ea25252368367a12af37df4ad6937763ce51a561b8d2"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.aarch64-linux-gnu.tar.gz"
[[libbluray]]
arch = "aarch64"
git-tree-sha1 = "c86d2630314bb10e4893350c0403c1bd6e7ba1cb"
libc = "musl"
os = "linux"

    [[libbluray.download]]
    sha256 = "8e7e937b0bc0222d284de9e9fa8a409f879fac3ed60e8a8d27a455611fad70c1"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.aarch64-linux-musl.tar.gz"
[[libbluray]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f77cab042f41cd251cb6c0c631438ae231cc859a"
libc = "glibc"
os = "linux"

    [[libbluray.download]]
    sha256 = "02f43277c199a459ceae82285aeb191d987d7c3695d688d10f27c68e7fccaa80"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[libbluray]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90d1f6bc17fe7a11ff63b865038a4499a732e761"
libc = "musl"
os = "linux"

    [[libbluray.download]]
    sha256 = "f48cd67efad3fed121ccc5a537db0790f248d1f54d4b9111a04a8ae27818ec99"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[libbluray]]
arch = "i686"
git-tree-sha1 = "042c26f4932ebc2aca04ef1f9d258291f1612f3e"
libc = "glibc"
os = "linux"

    [[libbluray.download]]
    sha256 = "40431a49234001a370a070102c424851800f69944d6c337639b7b57652cd2b3e"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.i686-linux-gnu.tar.gz"
[[libbluray]]
arch = "i686"
git-tree-sha1 = "9e193d0e5170871ac7b31d79c6cb5f73fe95f85d"
libc = "musl"
os = "linux"

    [[libbluray.download]]
    sha256 = "63013d0fa329aee5c7a9b73bda67d0205f4dbfce1b40b168370a7cb6ce78c313"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.i686-linux-musl.tar.gz"
[[libbluray]]
arch = "powerpc64le"
git-tree-sha1 = "357ac06480cda7e9ed0d26eae528ceb74fd06c71"
libc = "glibc"
os = "linux"

    [[libbluray.download]]
    sha256 = "20fca6c0ddc286306d38545ebdbb2ac8662ca7c3a207734f9e49e5382206526d"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[libbluray]]
arch = "x86_64"
git-tree-sha1 = "f2c8fdc493f001d15ff2081727d73e08c3030faf"
os = "macos"

    [[libbluray.download]]
    sha256 = "231cf727738b41a599f3b3903f5f019a55e15f71dd1d926e8f07b9b0b6e2d73b"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.x86_64-apple-darwin.tar.gz"
[[libbluray]]
arch = "x86_64"
git-tree-sha1 = "04bbc0963cab9e98780eb427068a59fcd7ef6bd9"
libc = "glibc"
os = "linux"

    [[libbluray.download]]
    sha256 = "79f7871d4c4284c7e8dfae05c9d8c2bfb76d1363855969771203e3efbfee04a6"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.x86_64-linux-gnu.tar.gz"
[[libbluray]]
arch = "x86_64"
git-tree-sha1 = "7f921661f645775c78317e749df4ffa26d483b15"
libc = "musl"
os = "linux"

    [[libbluray.download]]
    sha256 = "d3c697c3407018d0bfca170ceb6905f1248aee4d9acb5f7a20d13f479e854743"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.x86_64-linux-musl.tar.gz"
[[libbluray]]
arch = "x86_64"
git-tree-sha1 = "262d5c78322e4e7de3386a5fc491aa2ab1ee800b"
os = "freebsd"

    [[libbluray.download]]
    sha256 = "f7bc3009ea606dd453ed8b8fee77b3c27a4e58cd6678c8811e2b9a65377416e4"
    url = "https://github.com/JuliaBinaryWrappers/libbluray_jll.jl/releases/download/libbluray-v1.3.0+0/libbluray.v1.3.0.x86_64-unknown-freebsd.tar.gz"
